### ISSUE TITLE
How to get the running actions?

### ISSUE THREAD

**Issue by johhnry** [ArtFXDev/silex_client#150]
I am trying to solve #96 and I want to get the current running actions in the context.

I am trying to use:

https://github.com/ArtFXDev/silex_client/blob/921d1b0fb28e4f471c602ddbf5972e2fcc47898a/silex_client/core/context.py#L48

But it's not used in any code, is it up to date?

**Comment by Acedyn** [comment]
This is not used anymore, you can remove it and use context.actions instead

you could create a property

in ActionQuery:

```python
@property
def is_running(self): 
    return self._task is None or self._task.done():
```

in Context:

```python
@property
def running_actions(self):
    return [action for action in self.actions.values() if action.is_running]
```
or
```python
@property
def running_actions(self):
    return {key: action for key, action in self.actions.items() if action.is_running}
```
